apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: limitpolicies.oks.io
spec:
  group: oks.io
  names:
    kind: LimitPolicy
    listKind: LimitPolicyList
    plural: limitpolicies
    singular: limitpolicy
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  ephemeral-storage:
                    type: string
    subresources:
      status: {}
